// hel_react/src/Holl.jsx
import { useState } from 'react'
import "./Holl.css"

function Holl() {
  const [mine, setMine] = useState("..")
  const [com, setCom] = useState("..")
  const [res, setRes] = useState("..")

  const myclick=()=>{
         let rnd = Math.random();
         let newcom;
         console.log(rnd)
		if(rnd>0.5){
            newcom="홀";
        }
		else{
             newcom="짝";
        }

        setCom(newcom)
      console.log("mine"+mine)
      console.log("com"+com)

		if(mine==newcom){
            setRes("이김");
		}
		else{
			setRes("짐");
		}
  }


  return (
    <>
      <table>
        <tbody>
          <tr>
            <td>나</td>
            <td>
              <input type="text" value={mine} onChange={e => setMine(e.target.value)} />
            </td>
          </tr>
          <tr>
            <td>컴</td>
            <td>
              <input type="text" value={com} readOnly />
            </td>
          </tr>
          <tr>
            <td>결과</td>
            <td>
              <input type="text" value={res} readOnly />
            </td>
          </tr>
          <tr>
              <td colSpan="2">
                  <input onClick={myclick} type="button" value="게임하기"/>
              </td>
          </tr>
        </tbody>
      </table>
    </>
  )
}

export default Holl

// hel_vue/src/components/Holl.vue
<script setup>
import {ref} from 'vue'


const mine = ref("..")
const com = ref("..")
const res = ref("..")
const myclick = () =>{
    let rnd = Math.random();
		if(rnd>0.5){
			com.value="홀";
		}
		else{
			com.value="짝";
		}

		if(mine.value==com.value){
			res.value="이김";
		}
		else{
			res.value="짐";
		}
}

</script>

<template>
  <table >
    <tbody>
		<tr>
			<td>나</td>
			<td>
				<input type="text" v-model="mine" >
			</td>
		</tr>
		<tr>
			<td>컴</td>
			<td>
				<input type="text" :value="com" readonly>
			</td>
		</tr>
		<tr>
			<td>결과</td>
			<td>
				<input type="text" :value="res" readonly>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<input  type="button" value="게임하기" @click="myclick">
			</td>

		</tr>
    </tbody>
</table>



</template>

<style scoped>
   input[type='text']{
        width: 40px;
    }
    table, tr, td{
        border: 1px solid gainsboro;
    }
</style>
