// hel_vue/src/App.vue
<script setup>

import {ref} from "vue";
import MyInput from "./components/MyInput.vue";

const obj = ref(null);
const val = ref('hello')

const myclick=()=>{
  obj.value.value = "bye"
  val.value = 'bye'
}

</script>

<template>
  <input type="text" value="hello" ref="obj"/>
  <MyInput v-bind:value="val" ref="obj_value"/>
  <button @click="myclick">change Text</button>

</template>

<style scoped>

</style>

// hel_svelte/src/App.svelte
<script>

import MyInput from "./lib/MyInput.svelte";

let obj = null;
let text = "hello";

const myclick = () =>{
    obj.value = "bye"
    text="bye"
}
</script>

<main>
    <input type="text" value="hello" bind:this={obj}/><br/>
    <MyInput value={text} /><br/>
    <button onclick={myclick}>change Text</button><br/>


</main>

<style>


</style>
