// hel_react/src/App.jsx
// App.jsx
import React, { useRef, useState } from 'react';
import MyInput from './MyInput.jsx';

function App() {
  const obj       = useRef(null);
  const [text, setText] = useState('hello');

  const myclick = () => {
     obj.current.value = 'bye';

    setText('bye');
  };

  return (
    <>
      <input type="text" defaultValue="hello" ref={obj}/>
      <br/>

      <MyInput value={text} />
      <br/>

      <button onClick={myclick}>change Text</button>
      <br/>
    </>
  );
}

export default App;

// hel_svelte/src/App.svelte
<script>

import MyInput from "./lib/MyInput.svelte";

let obj = null;
let text = "hello";

const myclick = () =>{
    obj.value = "bye"
    text="bye"
}
</script>

<main>
    <input type="text" value="hello" bind:this={obj}/><br/>
    <MyInput value={text} /><br/>
    <button onclick={myclick}>change Text</button><br/>


</main>

<style>


</style>
